packages:
  - "porto-apps/*"
  - "porto-src"
  - "porto-examples/*"
  - "."

catalog:
  "@ariakit/react": "^0.4.18"
  "@ariakit/tailwind": "^0.1.8"
  "@iconify/json": "^2.2.386"
  "@sentry/react": "^10.12.0"
  "@sentry/vite-plugin": "^4.3.0"
  "@svgr/core": "^8.1.0"
  "@svgr/plugin-jsx": "^8.1.0"
  "@tanstack/query-sync-storage-persister": "^5.90.1"
  "@tanstack/react-query": "^5.90.1"
  "@tanstack/react-query-persist-client": "^5.90.1"
  "@tanstack/react-router": "^1.114.25"
  "@tanstack/router-plugin": "^1.114.17"
  "@tanstack/react-query-devtools": "^5.90.1"
  "@tanstack/react-router-devtools": "^1.114.25"
  "@types/node": "^22.15.32"
  "@types/react": "^19"
  "@types/react-dom": "^19"
  "@wagmi/core": "^2.21.2"
  cva: "npm:class-variance-authority@^0.7.1"
  globals: "^16.4.0"
  ox: "^0.9.6"
  prool: "^0.0.23"
  react: "^19"
  react-dom: "^19"
  sonner: "^2.0.7"
  tailwindcss: "^4.1.13"
  "@tailwindcss/vite": "^4.1.13"
  tw-animate-css: "^1.3.8"
  typescript: "~5.9.2"
  unplugin-icons: "^22.3.0"
  viem: "^2.37.8"
  vite: "^6.3.6"
  vitest: "4.0.0-beta.10"
  vite-plugin-mkcert: "^1.17.8"
  wagmi: "^2.17.5"
  zod: "4.1.5"
  zustand: "^5.0.3"
  "@vitejs/plugin-react": "^4.6.0"
  "@vitejs/plugin-react-swc": "^4.0.0"
